import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion, useInView } from 'framer-motion'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import Lenis from 'lenis'
import { ArrowDown, ArrowUpRight, Check, ChevronRight, Circle, Code2, Copy, Linkedin, Moon, Send, Sun, TerminalSquare } from 'lucide-react'
import pt from './content/pt.json'
import en from './content/en.json'
import { usePreferences } from './hooks/usePreferences'
const VisualField = lazy(() => import('./components/VisualField'))
gsap.registerPlugin(ScrollTrigger)
const skills = ['React','TypeScript','Python','Django','Django REST','Material UI','Tailwind','Docker','Redis','Celery','SQL Server','SAP ECC','SAP IDoc','OData','Linux','Git','Bitbucket','WSL']
const projects = [{title:'Warehouse Management',desc:'Operação, inventário e rastreabilidade em um único fluxo.',tags:['React','Django','SAP']},{title:'Production Dashboard',desc:'Visibilidade da produção para decisões em tempo real.',tags:['TypeScript','REST API','SQL']},{title:'SAP Integrations',desc:'Integrações resilientes entre processos e dados críticos.',tags:['Python','IDoc','Celery']},{title:'Industrial Label Printing',desc:'Automação de impressão onde precisão é essencial.',tags:['React','Docker','SAP']}]
const nodes = ['SAP','IDoc','Python','Celery','SQL Server','REST API','React','Dashboard']
const terminalResponses: Record<string,string[]> = { help:['comandos: whoami · skills · projects · contact · social · experience · architecture · clear','easter eggs: sudo hire otavio · sudo coffee'], whoami:['Otávio Valasco','Software Engineer · Latin America'], skills:['React, TypeScript, Python, Django, SAP, Docker'], projects:['Warehouse Management · Production Dashboard · SAP Integrations'], contact:['ovalasco@gmail.com'], social:['github.com/otaviovalasco · linkedin.com/in/otaviovalasco'], experience:['Construindo aplicações corporativas para indústria.'], architecture:['SAP → IDoc → Python → Celery → SQL → API → React'], 'sudo hire otavio':['✓ Access granted. Let’s make it exceptional.'], 'sudo coffee':['☕ System performance increased by 200%.'], 'about --secret':['RAVEN // precision hidden in plain sight.'] }
type Content = typeof pt
function Reveal({children, className = ''}:{children:React.ReactNode;className?:string}) { const ref=useRef(null); const visible=useInView(ref,{once:true,margin:'-70px'}); return <motion.div ref={ref} className={className} initial={{opacity:0,y:24,filter:'blur(8px)'}} animate={visible?{opacity:1,y:0,filter:'blur(0px)'}:{}} transition={{duration:.75,ease:[.16,1,.3,1]}}>{children}</motion.div> }
function Label({children}:{children:string}) { return <p className="section-label"><span/> {children}</p> }
function Loader() { const [step,setStep]=useState(0); const lines=['INITIALIZING...','Loading React...','Loading Python...','Loading SAP...','Loading Portfolio...','Done.']; useEffect(()=>{const i=setInterval(()=>setStep(s=>s+1),210);return()=>clearInterval(i)},[]); return <AnimatePresence>{step<lines.length&&<motion.div className="loader" exit={{opacity:0,scale:1.05,transition:{duration:.45}}}>{lines.slice(0,step+1).map((x,i)=><motion.p initial={{opacity:0}} animate={{opacity:i===step?1:.4}} key={x}>{i===step&&<span>› </span>}{x}</motion.p>)}</motion.div>}</AnimatePresence> }
function Terminal({t}:{t:Content['terminal']}) { const [input,setInput]=useState(''); const [history,setHistory]=useState<string[]>([t.hint]); const command=(raw:string)=>{const value=raw.trim().toLowerCase();if(!value)return;if(value==='clear'){setHistory([]);setInput('');return}setHistory(h=>[...h,`$ ${raw}`,...(terminalResponses[value]||[`command not found: ${value}`])]);setInput('')}; return <Reveal><section className="terminal card"><div className="terminal-bar"><span/><span/><span/><b><TerminalSquare size={14}/>{t.title}</b></div><div className="terminal-body" aria-live="polite">{history.map((line,i)=><p key={i}>{line}</p>)}<form onSubmit={e=>{e.preventDefault();command(input)}}><span>$</span><input aria-label="Terminal command" value={input} onChange={e=>setInput(e.target.value)} autoComplete="off"/></form></div></section></Reveal> }
function App() {
 const {theme,setTheme,lang,setLang}=usePreferences(); const t=(lang==='pt'?pt:en) as Content; const [copied,setCopied]=useState(false); const [loaded,setLoaded]=useState(false); const [activeNode,setActiveNode]=useState('SAP');
 useEffect(()=>{const id=setTimeout(()=>setLoaded(true),1400); const lenis=new Lenis({lerp:.09}); let frame=0; const raf=(time:number)=>{lenis.raf(time);frame=requestAnimationFrame(raf)};frame=requestAnimationFrame(raf); return()=>{clearTimeout(id);cancelAnimationFrame(frame);lenis.destroy()}},[])
 useEffect(()=>{const ctx=gsap.context(()=>gsap.utils.toArray<HTMLElement>('.architecture-node').forEach((node,i)=>gsap.fromTo(node,{opacity:0,x:-20},{opacity:1,x:0,duration:.45,delay:i*.08,scrollTrigger:{trigger:'#architecture',start:'top 72%'}})));return()=>ctx.revert()},[])
 const typeWords=useMemo(()=>['React','Python','Django','SAP','Docker','TypeScript'],[]); const [word,setWord]=useState(0); useEffect(()=>{const i=setInterval(()=>setWord(w=>(w+1)%typeWords.length),1600);return()=>clearInterval(i)},[typeWords.length]);
 const copy=async()=>{await navigator.clipboard.writeText('ovalasco@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),1800)}
 return <><Loader/><a className="skip-link" href="#main">Skip to content</a><Suspense fallback={null}><VisualField/></Suspense><header className="nav"><a href="#top" className="logo" aria-label="Home">OV</a><nav>{(['about','skills','projects','experience','contact'] as const).map(k=><a key={k} href={`#${k}`}>{t.nav[k]}</a>)}</nav><div className="nav-controls"><button className="icon-button" onClick={()=>setTheme(theme==='dark'?'midnight':theme==='midnight'?'aurora':'dark')} aria-label="Change color theme">{theme==='dark'?<Moon size={16}/>:<Sun size={16}/>}</button><button className="language" onClick={()=>setLang(lang==='pt'?'en':'pt')}>{lang==='pt'?'EN':'PT'}</button><a className="resume" href="#contact">{t.nav.resume}<ArrowUpRight size={14}/></a></div></header><main id="main">
 <section id="top" className="hero"><div className="hero-copy"><motion.p initial={{opacity:0}} animate={{opacity:loaded?1:0}} className="eyebrow">{t.hero.eyebrow}</motion.p><h1>{t.hero.title.split('\n').map((x,i)=><span key={x}>{x}{i===0&&<i/>}</span>)}</h1><div className="role"><span>{t.hero.role}</span><AnimatePresence mode="wait"><motion.b key={typeWords[word]} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{typeWords[word]}</motion.b></AnimatePresence></div><a href="#projects" className="primary-button">{t.hero.cta}<ArrowUpRight size={17}/></a></div><a href="#about" className="scroll-cue">{t.hero.scroll}<ArrowDown size={15}/></a></section>
 <section id="about" className="section about"><Reveal><Label>{t.about.label}</Label><div className="about-grid"><div className="portrait">{<img src="/profile.png" alt="Otávio Valasco" onError={e=>{e.currentTarget.style.display='none'}}/>}<div className="portrait-mark">OV</div></div><div><h2>{t.about.title}</h2><p className="body-copy">{t.about.body}</p><p className="availability"><Circle size={9} fill="currentColor"/>{t.about.availability}</p></div></div></Reveal></section>
 <section id="skills" className="section"><Reveal><Label>{t.skills.label}</Label><h2>{t.skills.title}</h2></Reveal><div className="skill-grid">{skills.map((skill,i)=><Reveal key={skill}><article className="skill card" style={{'--i':i} as React.CSSProperties}><Code2 size={20}/><span>{skill}</span><ChevronRight size={15}/></article></Reveal>)}</div></section>
 <section id="architecture" className="section architecture"><Reveal><Label>System architecture</Label><h2>Every connection has a purpose.</h2></Reveal><div className="architecture-flow">{nodes.map((node,i)=><div key={node} className="architecture-step"><button onMouseEnter={()=>setActiveNode(node)} onFocus={()=>setActiveNode(node)} className={`architecture-node ${activeNode===node?'selected':''}`}>{node}<small>{activeNode===node?'Active component':''}</small></button>{i<nodes.length-1&&<div className="connector"/>}</div>)}</div></section>
 <section id="projects" className="section"><Reveal><Label>{t.projects.label}</Label><h2>{t.projects.title}</h2></Reveal><div className="project-grid">{projects.map((p,i)=><Reveal key={p.title}><article className="project card"><div className={`project-art art-${i}`}><span>0{i+1}</span><div/></div><div className="project-info"><p>{p.tags.join(' · ')}</p><h3>{p.title}</h3><span>{p.desc}</span><a href="#contact">{t.projects.view}<ArrowUpRight size={15}/></a></div></article></Reveal>)}</div></section>
 <section id="experience" className="section experience"><Reveal><Label>{t.experience.label}</Label><h2>{t.experience.title}</h2><div className="experience-list">{[['2024 — now','Software Engineer','Corporate applications · LATAM'],['2022 — 2024','Full Stack Developer','Industrial systems · Integrations'],['2020 — 2022','Software Developer','Interfaces · Automation']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></Reveal></section>
 <Terminal t={t.terminal}/>
 <section id="contact" className="section contact"><Reveal><Label>{t.contact.label}</Label><h2>{t.contact.title}</h2><div className="contact-grid"><a className="contact-card card" href="https://www.linkedin.com/in/otaviovalasco/" target="_blank" rel="noreferrer"><Linkedin/><span>LinkedIn</span><ArrowUpRight/></a><button className="contact-card card" onClick={copy}><Send/><span>{copied?t.contact.copied:'ovalasco@gmail.com'}</span>{copied?<Check/>:<Copy/>}</button></div></Reveal></section>
 </main><footer><span>© {new Date().getFullYear()} Otávio Valasco</span><span>RAVEN / DIGITAL SYSTEMS</span></footer></>
}
export default App
